name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: 'gen-lang-client-0308183579'
  REGION: 'europe-north1'
  SERVICE_NAME: 'olaiprojectv4'
  GAR_LOCATION: 'europe-north1'
  REPOSITORY: 'olaiproject-repo'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/90985564727/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'github-actions-sa@gen-lang-client-0308183579.iam.gserviceaccount.com'
  # Forces all JavaScript actions to execute on the Node.js 24 runtime
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
    - name: Build and Push Container
      run: |
        IMAGE_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: ${{ env.IMAGE_TAG }}
        flags: >-
          --allow-unauthenticated
          --execution-environment=gen2
          --add-volume=name=storage-vol,type=cloud-storage,bucket=olaiproject_price_data,readonly=false
          --add-volume-mount=volume=storage-vol,mount-path=/mnt/storage